symfony/src/Entity/Order.php
<?php declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Entity\OrderRepository")
 * @ORM\Table(name="wb_order")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="NONE")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(name="created_at", type="date_immutable")
     *
     * @var \DateTimeImmutable
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=OrderItem::class, mappedBy="order")
     *
     * @var Collection|OrderItem[]
     */
    private $items;

    /**
     * @var array|int[]
     */
    private $prices = [];

    /**
     * @throws \Exception
     */
    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId() : int
    {
        return $this->id;
    }

    /**
     * @return \DateTimeImmutable
     */
    public function getCreatedAt() : \DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * @return int
     */
    public function getTotal() : int
    {
        $this->initPrices();

        return array_sum($this->prices);
    }

    /**
     * @return int
     */
    public function getMeanPrice() : int
    {
        if ($this->items->isEmpty()) {
            return 0;
        }

        return (int) ($this->getTotal() / $this->items->count());
    }

    /**
     * @return int
     */
    public function getMedianPrice() : int
    {
        if ($this->items->isEmpty()) {
            return 0;
        }

        $this->initPrices();

        // If number of items is odd get middle value
        if (1 === count($this->prices) % 2) {
            $key = (int) round(count($this->prices) / 2, 0, PHP_ROUND_HALF_DOWN);

            return $this->prices[$key];
        }

        // If number of items is even get the mean of the middle 2 values
        $key1 = (int) (count($this->prices) / 2) - 1;
        $key2 = $key1 + 1;

        return (int) (($this->prices[$key1] + $this->prices[$key2]) / 2);
    }

    /**
     * @return Collection|OrderItem[]
     */
    public function getItems() : Collection
    {
        return $this->items;
    }

    /**
     * @param OrderItem $orderItem
     */
    public function addItem(OrderItem $orderItem) : void
    {
        if (!$this->items->contains($orderItem)) {
            $this->items->add($orderItem);
        }
    }

    /**
     * @param int $id
     * @param \DateTimeImmutable $createdAt
     * @return Order
     */
    public static function create(
        int $id,
        \DateTimeImmutable $createdAt
    ) : Order {
        $order = new static();
        $order->id = $id;
        $order->createdAt = $createdAt;

        return $order;
    }

    /**
     * Initialise array of prices for order items
     */
    private function initPrices() : void
    {
        if (!empty($this->prices) || $this->items->isEmpty()) {
            return;
        }

        foreach ($this->items as $orderItem) {
            $this->prices[] = $orderItem->getPrice();
        }

        sort($this->prices);
    }
}

symfony/templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if orders|length > 0 %}
        <nav>
            <form class="float-right ml-5" action="{{ path('orders.create') }}" method="POST">
                <button class="btn btn-outline-primary" type="submit">
                    Create New Order
                </button>
            </form>
            <ul class="pagination float-right">
                <li class="page-item {% if false == orders.hasPreviousPage %}disabled{% endif %}">
                    {% if orders.hasPreviousPage %}
                        <a class="page-link" href="{{ path('orders.index', {'page': orders.previousPage }) }}">
                            Previous
                        </a>
                    {% else %}
                        <a class="page-link" href="#">
                            Previous
                        </a>
                    {% endif %}
                </li>
                <li class="page-item {% if false == orders.hasNextPage %}disabled{% endif %}">
                    {% if orders.hasNextPage %}
                        <a class="page-link" href="{{ path('orders.index', {'page': orders.nextPage }) }}">
                            Next
                        </a>
                    {% else %}
                        <a class="page-link" href="#">
                            Next
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>

        <table class="table">
            <thead>
                <tr>
                    <th>Order Id</th>
                    <th>Created At</th>
                    <th>Number of Items</th>
                    <th>Total</th>
                    <th>Mean Price</th>
                    <th>Median Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <td>
                            <a href="{{ path('orders.show', {'id': order.id }) }}">
                                {{ order.id }}
                            </a>
                        </td>
                        <td>{{ order.createdAt|date('Y-m-d') }}</td>
                        <td>{{ order.items|length }}</td>
                        <td>&pound;{{ (order.total / 100)|number_format(2) }}</td>
                        <td>&pound;{{ (order.meanPrice / 100)|number_format(2) }}</td>
                        <td>&pound;{{ (order.medianPrice / 100)|number_format(2) }}</td>
                        <td>
                            <form action="{{ path('orders.delete', {'id': order.id }) }}" method="POST">
                                <input type="hidden" name="_method" value="DELETE" />
                                <button class="btn btn-outline-danger" type="submit">
                                    x
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            Database contains no orders. <a href="{{ path('app.init') }}">Initialise app</a>.
        </div>
    {% endif %}
{% endblock body %}

symfony/templates/app/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="card">
        <div class="card-header">
            Order #{{ order.id }}

            <div class="float-right">
                Created: {{ order.createdAt|date('Y-m-d') }}
            </div>
        </div>
        <div class="card-body text-center">
            <div class="row">
                <div class="col-sm">
                    <strong>Total</strong>
                    &pound;{{ (order.total / 100)|number_format(2) }}
                </div>
                <div class="col-sm">
                    <strong>Mean</strong>
                    &pound;{{ (order.meanPrice / 100)|number_format(2) }}
                </div>
                <div class="col-sm">
                    <strong>Median</strong>
                    &pound;{{ (order.medianPrice / 100)|number_format(2) }}
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row mt-5">
            <table class="table col-8">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Postage</th>
                        <th>Method</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for orderItem in order.items %}
                        <tr>
                            <td>{{ orderItem.name }}</td>
                            <td>&pound;{{ (orderItem.price / 100)|number_format(2) }}</td>
                            <td>
                                {% if orderItem.postage %}
                                    &pound;{{ (orderItem.postage / 100)|number_format(2) }}
                                {% else %}
                                    None
                                {% endif %}
                            </td>
                            <td>{{ orderItem.method ? orderItem.method|title : 'FREE' }}</td>
                            <td>
                                <form action="{{ path('order_items.delete', {'orderId': order.id, 'id': orderItem.id }) }}" method="POST">
                                    <input type="hidden" name="_method" value="DELETE" />
                                    <button class="btn btn-outline-danger" type="submit">
                                        x
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">
                                No items found.
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="offset-1 col-3">
                {% if form is defined %}
                    {{ form_start(form, {'attr': {'autocomplete': 'off'}}) }}
                        {{ form_row(form.name) }}
                        {{ form_row(form.price) }}
                        {{ form_row(form.postage) }}
                        {{ form_row(form.method) }}

                        {{ form_widget(form.submit, {'attr': {'class': 'btn-block btn-outline-primary'}}) }}

                        <a class="btn btn-block btn-outline-danger" href="{{ path('orders.show', {'id': order.id}) }}">
                            Cancel
                        </a>
                    {{ form_end(form) }}
                {% else %}
                    <div class="text-right">
                        <a class="btn btn-outline-primary btn-block" href="{{ path('order_items.create', {'orderId': order.id }) }}">
                            Add order item
                        </a>

                        <form class="mt-4" action="{{ path('orders.delete', {'id': order.id }) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE" />
                            <button class="btn btn-outline-danger btn-block" type="submit">
                                Delete Order
                            </button>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body %}